#include <Arduino.h>

// Industrial Shields RS-485 helper. On their ESP32 PLC boards this usually exposes a global `RS485` object.
// If your project uses a different name/instance, just pass that Stream to oriental.begin(...)
#include <RS485.h>

#include <VJ_OrientalMaster.h>

VJ_OrientalMaster oriental;

static void onOrientalEvent(uint8_t id, const char* msg) {
  // Example: print events to USB serial, but they are generated by the library.
  Serial.printf("M%u %s\r\n", id, msg);
}

// Example motion profile (user-units; will be scaled by MPA ratios)
static const uint8_t  MOTOR_ID = 1;
static const uint16_t OP_TYPE  = 3;       // Incremental positioning (based on feedback position)
static const int32_t  POS      = 100;     // user units
static const int32_t  SPD      = 5000;
static const int32_t  ACC      = 1500000;
static const int32_t  DEC      = 1500000;
static const uint16_t CUR      = 1000;    // 0..1000 (0.1%)

static uint32_t t0 = 0;
static bool sentOnce = false;

void setup() {
  Serial.begin(115200);
  delay(300);

  // RS485 settings: adjust to your AZD-C(D) comm settings.
  // Many AZ setups use 8E1.
  RS485.begin(115200, HALFDUPLEX, SERIAL_8E1);

  oriental.begin(RS485);
  oriental.setEventCallback(onOrientalEvent);
  oriental.setInterframeDelayMs(4);
  oriental.setPollIntervalMs(50);

  // Configure ratios (example):
  // R_POS=100 => any position you pass will be *100 before sending to drive
  // R_FBP=10  => feedback position read back will be /10
  oriental.MPA(MOTOR_ID,
               100,   // R_POS
               1,     // R_SPD
               1,     // R_ACC
               1,     // R_DEC
               1,     // R_CUR
               10,    // R_FBP
               10);   // R_CMP

  Serial.println("VJ_OrientalMaster example started");
  t0 = millis();
}

void loop() {
  oriental.update();

  // One-shot test: run once after 2 seconds
  if (!sentOnce && (millis() - t0) > 2000) {
    VJ_OrientalMaster::SMPFields f;
    f.hasOpType = true; f.opType = OP_TYPE;
    f.hasPos    = true; f.pos    = POS;
    f.hasSpd    = true; f.spd    = SPD;
    f.hasAcc    = true; f.acc    = ACC;
    f.hasDec    = true; f.dec    = DEC;
    f.hasCur    = true; f.cur    = CUR;

    bool ok = oriental.SMP(MOTOR_ID, f);
    Serial.printf("SMP -> %s\r\n", ok ? "OK" : "ERR");

    // Example: if alarm is set, pulse RESET
    bool alarm = false;
    if (oriental.GOU(MOTOR_ID, VJ_OrientalMaster::ALARM, alarm) && alarm) {
      Serial.println("Alarm present -> SIP(RESET)");
      oriental.SIP(MOTOR_ID, VJ_OrientalMaster::RESET);
    }

    sentOnce = true;
  }

  // Every 1s print positions
  static uint32_t lastPrint = 0;
  if (millis() - lastPrint > 1000) {
    lastPrint = millis();

    int32_t fbp = 0, cmp = 0;
    if (oriental.GFP(MOTOR_ID, fbp) && oriental.GCP(MOTOR_ID, cmp)) {
      Serial.printf("FBP=%ld  CMP=%ld\r\n", (long)fbp, (long)cmp);
    }
  }
}
